In [2]:
import numpy as np
import sys

print(f"NumPy version: {np.__version__}")
print(f"Python version: {sys.version[:6]}")
print("Day 3 - NumPy")

NumPy version: 2.4.4
Python version: 3.11.1
Day 3 - NumPy


In [4]:
import time

# Python list
py_list =list(range(1_000_000))

# NumPy array
np_array = np.array(range(1_000_000))

# Memory comparison
import sys
print("=== Memory ====")
print(f"Python list: {sys.getsizeof(py_list):,} bytes")
print(f"NumPy array: {np_array.nbytes:,} bytes")

#Speed Comparison - multiply every element by 2
print("\n === Speed ===")

#List way - loop
start = time.time()
result_list = [x*2 for x in py_list]
list_time= time.time() - start
print(f"List comprehension: {list_time:.4f}s")

#Numpy way - vectorized
start = time.time()
result_array = np_array * 2
numpy_time = time.time() - start
print(f"NumPy vectorized: {numpy_time:.4f}s")

print(f"\n NumPy is {list_time/numpy_time}X faster")

=== Memory ====
Python list: 8,000,056 bytes
NumPy array: 8,000,000 bytes

 === Speed ===
List comprehension: 0.0635s
NumPy vectorized: 0.0031s

 NumPy is 20.719418306244652X faster


In [6]:
import numpy as np

python_list = [1,2,3,4,5]

numpy_array = np.array([1,2,3,4,5])

print("=== Data Types ===")
print(f"List element type: {type(python_list[0])}")
print(f"Array element type: {type(numpy_array[0])}")
print(f"Array dtype: {numpy_array.dtype}")

print("\n=== Array Properties ===")
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(f"Array:\n{arr}")
print(f"Shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Total elements: {arr.size}")
print(f"Data Type : {arr.dtype}")


=== Data Types ===
List element type: <class 'int'>
Array element type: <class 'numpy.int64'>
Array dtype: int64

=== Array Properties ===
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Total elements: 9
Data Type : int64


In [9]:
#Zeros - initialize embedding matrix before filling
embedding_matrix = np.zeros((5,4)) #chunks, 4-dim embeddings
print("Zeros(embedding matrix):")
print(embedding_matrix)

#Ones - useful for masks
mask = np.ones((3,3))
print("\n Ones (mask):")
print(mask)

# Random - simulate embedding vectors
np.random.seed(42) #seed for reproducibility
fake_embeddings = np.random.uniform(-1, 1, size=(4,6))
print("\n Random embeddings (4 chunks, 6 dimensions): ")
print(fake_embeddings)
print(f"shape: {fake_embeddings.shape}")

# Arange - like python range returns array
indices = np.arange(0,10,2)
print(f"\nArange (even numbers): {indices}")

# Linspace -evenly spaced values
scores = np.linspace(0,1,5) #5 similarity scores between 0 and 1
print(f"Linspace (similarity scores): {scores}")

Zeros(embedding matrix):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 Ones (mask):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Random embeddings (4 chunks, 6 dimensions): 
[[-0.25091976  0.90142861  0.46398788  0.19731697 -0.68796272 -0.68801096]
 [-0.88383278  0.73235229  0.20223002  0.41614516 -0.95883101  0.9398197 ]
 [ 0.66488528 -0.57532178 -0.63635007 -0.63319098 -0.39151551  0.04951286]
 [-0.13610996 -0.41754172  0.22370579 -0.72101228 -0.4157107  -0.26727631]]
shape: (4, 6)

Arange (even numbers): [0 2 4 6 8]
Linspace (similarity scores): [0.   0.25 0.5  0.75 1.  ]


In [11]:
import time

# Scenario: calculate the length (magnitude) of 1 million vectors
# This is doen thousands of times during embedding similarity search

data = np.random.uniform (-1, 1, size= (1_000_000, 3))

# Bad way - Python loop
def magnitude_loop(vectors):
    results = []
    for vec in vectors:
        magnitude =0
        for val in vec:
            magnitude += val ** 2
        results.append(magnitude ** 0.5)
    return results

# Good Way - NumPy vectorized
def magnitude_vectorized(vectors):
    return np.sqrt(np.sum(vectors ** 2, axis=1))

# Compare speed
print("Calculating magnitude of 1 million vetors....\n")

start=time.time()
loop_result = magnitude_loop(data)
loop_time = time.time()-start
print(f"Loop time {loop_time:.4f}s")

start=time.time()
vec_result = magnitude_vectorized(data)
vec_time = time.time() - start
print(f"Vectorized time: {vec_time:.4f}s")

print(f"\nSpeedup: {loop_time/vec_time:.1f}x faster")
print(f"First 5 results match: {np.allclose(loop_result[:5], vec_result[:5])}")

Calculating magnitude of 1 million vetors....

Loop time 2.7552s
Vectorized time: 0.0549s

Speedup: 50.2x faster
First 5 results match: True


In [16]:
# Broadcasting lets you do math between arrays of different shapes
# NumPy stretches the smaller array to match the larger one

# Scenario: normalize all embedding vectors
# Each vector needs to be divided by its own magnitude

np.random.seed(42)
embeddings = np.random.uniform(-1, 1, size=(5,4))
print("Original embeddings:")
print(embeddings)
print(f"Shape: {embeddings.shape}")

# Calculate magnitude of each vector - shape becomes (5,)
magnitudes= np.sqrt(np.sum(embeddings**2, axis=1))
print(f"\n Magnitude shape: {magnitudes.shape}")
print(f"Magnitude: {magnitudes}")

# Reshape for broadcasting - need (5,1) not (5,)
magnitudes_reshaped = magnitudes.reshape(5, 1)
print(f"\n Reshaped magnitude: {magnitudes_reshaped.shape}")

#Divide each row by its magnitude - broadcasting handles the rest 
normalized = embeddings / magnitudes_reshaped
print(f"\n Normalized embeddings:")
print(normalized)

#verify - magnitude of eaach normalized vector should be 1.0
check = np.sqrt(np.sum(normalized**2, axis=1))
print(f"\n Magnitude after normalization( should all be 1.0):")
print(np.round(check, 6))

Original embeddings:
[[-0.25091976  0.90142861  0.46398788  0.19731697]
 [-0.68796272 -0.68801096 -0.88383278  0.73235229]
 [ 0.20223002  0.41614516 -0.95883101  0.9398197 ]
 [ 0.66488528 -0.57532178 -0.63635007 -0.63319098]
 [-0.39151551  0.04951286 -0.13610996 -0.41754172]]
Shape: (5, 4)

 Magnitude shape: (5,)
Magnitude: [1.0628984  1.50470995 1.42010273 1.25655872 0.59042606]

 Reshaped magnitude: (5, 1)

 Normalized embeddings:
[[-0.23607126  0.8480854   0.43653079  0.18564048]
 [-0.4572062  -0.45723826 -0.5873775   0.48670662]
 [ 0.14240521  0.29303877 -0.67518426  0.66179699]
 [ 0.52913188 -0.45785507 -0.50642286 -0.50390879]
 [-0.66310677  0.08385955 -0.23052838 -0.70718715]]

 Magnitude after normalization( should all be 1.0):
[1. 1. 1. 1. 1.]


In [3]:
# Cosine similarity measures the angle between two vectors
# Score of 1.0 = identical directions = very similar meaning
# Score of 0.0 = perpendicualr = unrelated
# Score of-1.0 = opposite direction = opposite meaning

import numpy as np

def cosine_similarity(vec1: np.ndarray, vec2: np.ndarray)->float:
    """Calculate similarity between two embedding vectors"""
    dot_product = np.dot(vec1, vec2)
    magnitude1 = np.sqrt(np.sum(vec1**2))
    magnitude2 = np.sqrt(np.sum(vec2**2))
    return dot_product / (magnitude1 * magnitude2)

def cosine_similarity_matrix(query: np.ndarray, docs: np.ndarray)-> np.ndarray:
    """
    Calculate Similarity between one query and ALL documents at once.
    This is what your retriever does on every search.
    """

    #Normalize query
    query_norm = query / np.sqrt(np.sum(query**2))

    # Normalize all docs at once - broadcasting
    doc_magnitudes = np.sqrt(np.sum(docs**2 , axis=1, keepdims=True))
    docs_norm = docs / doc_magnitudes

    #Dot product - query against every doc simultaneously
    return np.dot(docs_norm, query_norm)

# Simulate a real RAG search
np.random.seed(42)

# Fake document chunks and their embeddings
chunks = [
    "RAG combines retrieval and Generation",
    "Vector Databases store embeddings",
    "Python is a programming language",
    "Rag uses semantic search for retrieval",
    "Fine tuning adapts pretrained models"
]

# Simulate embeddings (in real life these come from openAI)
doc_embeddings = np.random.uniform(-1, 1, size=(5,8))

# Simulate query embeddings
query = "how does RAG work?"
query_embedding = np.random.uniform(-1, 1, size=(8,))

# Calculate similarities 
similarities = cosine_similarity_matrix(query_embedding, doc_embeddings)

print("=== RAG Similarity Search ===")
print(f"Query: '{query}'\n")

# Rank by similarity
ranked_indices = np.argsort(similarities)[::-1]

print("Ranked results: ")
for rank , idx in enumerate(ranked_indices):
    print(f"   Rank {rank+1} | Score: {similarities[idx]:.4f} | {chunks[idx]}")

print(f"\nTop result: '{chunks[ranked_indices[0]]}'")
print(f"Score: {similarities[ranked_indices[0]]:.4f}")

=== RAG Similarity Search ===
Query: 'how does RAG work?'

Ranked results: 
   Rank 1 | Score: 0.3970 | Vector Databases store embeddings
   Rank 2 | Score: 0.1285 | RAG combines retrieval and Generation
   Rank 3 | Score: 0.0663 | Rag uses semantic search for retrieval
   Rank 4 | Score: 0.0224 | Fine tuning adapts pretrained models
   Rank 5 | Score: -0.0669 | Python is a programming language

Top result: 'Vector Databases store embeddings'
Score: 0.3970


In [7]:
from typing import List, Tuple

def retrieve_top_k(
        query_embedding: np.ndarray,
        doc_embeddings: np.ndarray,
        chunks: List[str],
        k: int = 3,
        threshold: float = 0.0,
)-> List [Tuple[str, float]]:
    """
    Retrieve top-k most similiar chunks to a query.

    Args:
        query_embedding: embedding vector for the query
        doc_embeddings: matrix of all document embeddings
        chunks: list of original text chunks
        k: number of results to return
        threshold: minimum similarity score to include

        Returns:
        List of (chunk_text, similarity_score) tuples
    """

    # Calculate all similarities at once
    similarities = cosine_similarity_matrix(query_embedding, doc_embeddings)

    #Get top  k indices
    top_k_indices = np.argsort(similarities)[::-1][:k]

    # Builds results - filter by threshold
    results = []
    for idx in top_k_indices:
        score = float(similarities[idx])
        if score >= threshold:
                results.append((chunks[idx], score))

    return results

# Test with different k and threshold values
np.random.seed(42)
doc_embeddings = np.random.uniform(-1, 1, size=(5,8))
query_embedding = np.random.uniform(-1, 1, size=(8,))

chunks = [
     "RAG combines retrieval and generation",
     "Vector Databases store embeddings",
     "Python is a programming language",
     "Fine tuning adapts pretrained models",
     "RAG uses semantic search for retrieval"
]

print("=== Top 3 results(no threshold) ===")
results = retrieve_top_k(query_embedding, doc_embeddings, chunks, k=3)
for chunk, score in results:
     print(f"   [{score:.4f}] {chunk}")

print("=== Top 3 results (threshold = 0.05) ===")
results = retrieve_top_k(query_embedding, doc_embeddings, chunks, k=3, threshold=0.05)
for chunk, score in results:
     print(f" [{score:.4f}] {chunk}")

print("=== Top 5 results (threshold = 0.1) ===")
results = retrieve_top_k(query_embedding, doc_embeddings, chunks, k=5, threshold=0.1)
for chunk, score in results:
     print(f" [{score:.4f}] {chunk}")





=== Top 3 results(no threshold) ===
   [0.3970] Vector Databases store embeddings
   [0.1285] RAG combines retrieval and generation
   [0.0663] Fine tuning adapts pretrained models
=== Top 3 results (threshold = 0.05) ===
 [0.3970] Vector Databases store embeddings
 [0.1285] RAG combines retrieval and generation
 [0.0663] Fine tuning adapts pretrained models
=== Top 5 results (threshold = 0.1) ===
 [0.3970] Vector Databases store embeddings
 [0.1285] RAG combines retrieval and generation
